language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
before_script:
    - sudo apt-get update -y
    - sudo apt-get -y install zip unzip
script:
    - sudo apt-get --quiet install --yes python-pip
    - sudo pip install -U pip
    - sudo pip install awscli
    - sudo zip -r app.zip .
    - sudo aws configure set aws_access_key_id $AWS_ACCESS_KEY
    - sudo aws configure set aws_secret_access_key $AWS_SECRET_KEY
    - sudo aws s3 cp app.zip s3://travisci-codepipeline-deployment-22-06-2021/my_app.zip
deploy:
  provider: codedeploy
  bucket: travisci-codepipeline-deployment-22-06-2021
  region: eu-central-1
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  key: my_app.zip
  bundle_type: zip
  application: DemoApplicationTravisCI
  deployment_group: DemoAppTravisCIDeploymentGroup
