language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
before_script:
    - apt-get update -y
    - apt-get -y install zip unzip
script:
    - sudo apt-get --quiet install --yes python-pip
    - pip install -U pip
    - pip install awscli
    - zip -r app.zip .
    - aws s3 cp app.zip s3://travisci-codepipeline-deployment-22-06-2021/my_app.zip
deploy:
  provider: codedeploy
  bucket: travisci-codepipeline-deployment-22-06-2021
  key: my_app.zip
  bundle_type: zip
  application: DemoApplicationTravisCI
  deployment_group: DemoAppTravisCIDeploymentGroup
