language: node_js
node_js:
- node
deploy:
  matrix:
  - provider: s3
  - provider: codedeploy
    access_key_id: AKIAYRMBFYNCQ7KXGGMO
    secret_access_key: 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
    bucket: travisci-codepipeline-deployment-22-06-2021
    key: my_app.zip
    application: DemoApplicationTravisCI
    deployment_group: DemoAppTravisCIDeploymentGroup
  secret_access_key:
    secure: Sc6wGMhQ0Ae/tKvg9FSZxKPnOt3TNFMA8AQtnO/7R8Qe7KY8spmdbg1hdFuUilYxxs4nb4yxN0OMJncS2Lu48R2o+vcWCV2Z0FcX3bBYNREXmD2EMYfj1EnWun2HF6QSlNWlXHOMA8QJ2NXCeIxpLvyZv0bN7SilgwMybdLwDpYTSpZ0IBHm0p9w/lV/VhEFmtxlp7RdOhZpdeRUSJpKvaC4XrpS/+gSJXl9KikBitqBQX1+PG0H7gJPYzUUcX+0Uq87DCtIWA3MMKyN0rb3c/BZACORZP9Gw+vnfKL/YqcUeFGKxLTOr/Ns2edp9W9hXk8P85EDh+BYBXCTyqDHIkLbtUmuk3umwrcHBpOskjRoDXRDyL62b6mk4KzE9sCfufcMVE5p1Ayh/3zsOqjitX1SYKx6VmBZ+2ldRRKhnxFi3yexrbEyya2VuaPUPTHmI6C/xbBbHDCReGSsGpfufvIALuhvs4kpxc7IlLtwnKEPRrQM5Jow4Dv4DGK6oST1T3KInhbLxIoW1xosCLgcU454YK0a+6VW1QQQzp4G1gso2J64ElTR64R3LlCoUKlW0oyt8YOs644oPcGXbYwCWEQ3huT/8FIefydKjiBISypWr/9iWlQPrOx3O7vgkq6WNRrj+g8U0RbWOopUffAlGZk66pAWhvS+WKhmhlPLsgc=
