language: node_js
node_js:
- node

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
  bucket: travisci-codepipeline-deployment-22-06-2021
  region: eu-central-1
  provider: codedeploy
  bucket: travisci-codepipeline-deployment-22-06-2021
  key: my_app.zip
  bundle_type: zip
  application: DemoApplicationTravisCI
  deployment_group: DemoAppTravisCIDeploymentGroup